fix isolate.py
isolate.py is currently broken as it attempts to create config without namespace

Traceback (most recent call last):
  File "./cmk.py", line 216, in <module>
    main()
  File "./cmk.py", line 151, in main
    isolate.isolate(args["--pool"],
  File "/cmk/intel/isolate.py", line 151, in isolate
    c = config.Config(configmap_name, pod_name)
TypeError: __init__() missing 1 required positional argument: 'cm_namespace'